### ISSUE TITLE
dividing by zero

### ISSUE THREAD

**Issue by londumas** [vatsalsharan/pidforest#3]
The following code results in the following error because of division by zero.

https://github.com/vatsalsharan/pidforest/blob/ee768d1d58b68b01d607a9740b9a0805a8512b1a/code/run_classification_pyod.py#L62

```
run_classification_pyod.py:61: RuntimeWarning: invalid value encountered in true_divide
  precision_all[j,0] = max(2*precision_iso*recall_iso/(precision_iso+recall_iso))
run_classification_pyod.py:62: RuntimeWarning: invalid value encountered in true_divide
  precision_all[j,1] = max(2*precision_lof*recall_lof/(precision_lof+recall_lof))
```

**Comment by londumas** [comment]
Same here:
```
run_classification_rrcf.py:69: RuntimeWarning: invalid value encountered in true_divide
  precision_all[j,0] = max(2*precision_iso*recall_iso/(precision_iso+recall_iso))
```

```
run_classification_sklearn_pidforest_alg.py:84: RuntimeWarning: invalid value encountered in true_divide
  precision_all[j,1] = max(2*precision_lof*recall_lof/(precision_lof+recall_lof))
run_classification_sklearn_pidforest_alg.py:85: RuntimeWarning: invalid value encountered in true_divide
  precision_all[j,2] = max(2*precision_osvm*recall_osvm/(precision_osvm+recall_osvm))
run_classification_sklearn_pidforest_alg.py:86: RuntimeWarning: invalid value encountered in true_divide
  precision_all[j,3] = max(2*precision_our*recall_our/(precision_our+recall_our))
```

```
run_timeseries_pyod.py:64: RuntimeWarning: invalid value encountered in true_divide
  precision_all[j,0] = max(2*precision_iso*recall_iso/(precision_iso+recall_iso))
run_timeseries_pyod.py:65: RuntimeWarning: invalid value encountered in true_divide
  precision_all[j,1] = max(2*precision_lof*recall_lof/(precision_lof+recall_lof))
```

**Comment by londumas** [comment]
The incorrect division must be preventing from the script to finish properly:

```
python run_classification_rrcf.py
```

```
Traceback (most recent call last):
  File "run_classification_rrcf.py", line 67, in <module>
    precision_iso, recall_iso, thresholds_iso = metrics.precision_recall_curve(y, iso_scores, pos_label=1)
  File "<HOME>.local/lib/python3.6/site-packages/sklearn/metrics/_ranking.py", line 673, in precision_recall_curve
    sample_weight=sample_weight)
  File "<HOME>.local/lib/python3.6/site-packages/sklearn/metrics/_ranking.py", line 542, in _binary_clf_curve
    assert_all_finite(y_score)
  File "<HOME>.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 77, in assert_all_finite
    _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
  File "<HOME>.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 60, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```
